#!/bin/bash

function foreach() {
    f=$1
    shift
    xs=$@
    for x in $xs;
    do
        $f $x
    done
}

function link_name() {
    echo ~/\.`basename $1 | sed 's/^\(.*\).link$/\1/'`
}

function clean() {
    file=`link_name $1`
    echo "> cleaning $1"
    rm -f $file
}

function check_if_exists() {
    file=`link_name $1`
    echo -n "> checking $file ... "
    if [ -e "$file" ];
    then
        echo "already exits, aborting!"
        exit "1"
    fi
    echo "ok"
}

function install() {
    original=$1
    link=`link_name $original`
    echo "> installing $original -> $link"
    ln -s `pwd`/$original $link
}

files=(`find . -name '*.link' | grep -v '/.git/'`)


echo "cleaning ..."
foreach "clean" ${files[@]}
echo "checking if all files can be linked ..."
foreach "check_if_exists" ${files[@]}
echo "looks fine, friend!"
echo "installing files ..."
foreach "install" ${files[@]}
echo "all done!"
