#!/bin/bash

SYNCED_DIR="$HOME/Dropbox/dotfiles_data"

function foreach() {
    f=$1
    shift
    xs=$@
    for x in $xs;
    do
        $f $x
    done
}

function link_name() {
    basename $1 | sed 's/^\(.*\).link$/\1/'
}

function link_path() {
    echo $HOME/\.`link_name $1`
}

function clean() {
    original=$1
    link_name=`link_name $original`
    link_path=`link_path $original`
    on_clean="$original/on_clean_hook.sh"
    if [ -e $on_clean ];
    then
        echo "    >> running $on_clean: $on_link"
        $on_clean $link_name $link_path $SYNCED_DIR
    fi
    echo "> cleaning $link_path"
    rm -f $link_path

}

function check_if_exists() {
    file=`link_path $1`
    echo -n "> checking $file ... "
    if [ -e "$file" ];
    then
        echo "already exits, aborting!"
        exit "1"
    fi
    echo "ok"
}

function install() {
    original=$1
    link_name=`link_name $original`
    link_path=`link_path $original`
    on_link="$original/on_link_hook.sh"

    echo "> installing $original -> $link_path"
    ln -s `pwd`/$original $link_path

    if [ -e $on_link ];
    then
        echo "    >> running $on_link: $on_link"
        $on_link $link_name $link_path $SYNCED_DIR
    fi
}

files=(`find . -name '*.link' | grep -v '/.git/'`)


echo "cleaning ..."
foreach "clean" ${files[@]}
echo "checking if all files can be linked ..."
foreach "check_if_exists" ${files[@]}
echo "looks fine, friend!"
echo "installing files ..."
foreach "install" ${files[@]}
echo "all done!"

echo "updating submodules"
git submodule init
git submodule update

./install-brew.sh
